#
# Warning! This file has been generated by the BlackBerry Java Development environment.
# Do not modify by hand.
#

all: \


clean:
	@if exist FindLocation.cod erase FindLocation.cod > nul
	@if exist FindLocation.lst erase FindLocation.lst > nul
	@if exist FindLocation.debug erase FindLocation.debug > nul
	@if exist FindLocation.wts erase FindLocation.wts > nul
	@if exist FindLocation.cso erase FindLocation.cso > nul
	@if exist FindLocation.csl erase FindLocation.csl > nul
	@if exist FindLocation-*.lst erase FindLocation-*.lst > nul
	@if exist FindLocation-*.debug erase FindLocation-*.debug > nul

rebuild: clean all

Private: \


Private_files:


Debug: \


Debug_files:


Release: \
    FindLocation.cod \


Release_files:
	@echo F:\blackberry\CallAssistant\FindLocation


FindLocation_sources = \
    src\ConcretePhoneListener.java \
    src\Const.java \
    src\FindLocation.java \
    src\Global.java \
    src\ShowScreen.java \
    src\Utils.java \

FindLocation_dependencies = \
    FindLocation.jdp \
    FindLocation.rapc \
    "E:\DevelopTools\Research In Motion\BlackBerry JDE 4.3.0\lib\net_rim_api.jar" \

FindLocation.cod : $(FindLocation_sources) $(FindLocation_dependencies)
	@if exist FindLocation.cod erase FindLocation.cod > nul
	@if exist FindLocation.lst erase FindLocation.lst > nul
	@if exist FindLocation.debug erase FindLocation.debug > nul
	@if exist FindLocation.wts erase FindLocation.wts > nul
	@if exist FindLocation.cso erase FindLocation.cso > nul
	@if exist FindLocation.csl erase FindLocation.csl > nul
	@if exist FindLocation-*.lst erase FindLocation-*.lst > nul
	@if exist FindLocation-*.debug erase FindLocation-*.debug > nul
	@echo Building FindLocation ...
	@"E:\DevelopTools\Research In Motion\BlackBerry JDE 4.3.0\bin\rapc.exe"  -quiet import="E:\DevelopTools\Research In Motion\BlackBerry JDE 4.3.0\lib\net_rim_api.jar" codename=FindLocation FindLocation.rapc $(FindLocation_sources)
	@if exist "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.cod" erase "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.cod" > nul
	@if exist FindLocation.cod copy FindLocation.cod "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.cod" > nul
	@if exist "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.jar" erase "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.jar" > nul
	@if exist FindLocation.jar copy FindLocation.jar "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.jar" > nul
	@if exist "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.lst" erase "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.lst" > nul
	@if exist FindLocation.lst copy FindLocation.lst "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.lst" > nul
	@if exist "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.debug" erase "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.debug" > nul
	@if exist FindLocation.debug copy FindLocation.debug "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.debug" > nul
	@if exist "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.wts" erase "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.wts" > nul
	@if exist FindLocation.wts copy FindLocation.wts "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.wts" > nul
	@if exist "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.cso" erase "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.cso" > nul
	@if exist FindLocation.cso copy FindLocation.cso "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.cso" > nul
	@if exist "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.csl" erase "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.csl" > nul
	@if exist FindLocation.csl copy FindLocation.csl "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation.csl" > nul
	@if exist "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation-*.lst" erase "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation-*.lst" > nul
	@if exist FindLocation-*.lst copy FindLocation-*.lst "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation-*.lst" > nul
	@if exist "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation-*.debug" erase "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation-*.debug" > nul
	@if exist FindLocation-*.debug copy FindLocation-*.debug "E:\DevelopTools\BlackBerry Device Simulators 4.2.2\4.2.2.114 (8300-Vodafone)\FindLocation-*.debug" > nul


